import prisma from '../utils/prismaClient';

// --- Summary Creation Data Type ---
interface CreateSummaryInput {
  originalFilePath: string; // Path of the uploaded file
  summaryText: string;      // The generated summary content
  creatorId: string;        // From authenticated user
}

// --- Service Functions ---

export const createSummary = async (data: CreateSummaryInput) => {
  const { originalFilePath, summaryText, creatorId } = data;

  if (!originalFilePath || !summaryText || !creatorId) {
    throw new Error('Missing required fields for summary creation');
  }

  // --- Placeholder Integration Point --- 
  // Before saving, the summaryText provided here would have been
  // generated by your NLP/AI logic using the content extracted from
  // originalFilePath in the controller.
  // --- End Placeholder --- 

  return prisma.summary.create({
    data: {
      originalFilePath,
      summaryText, // Save the AI-generated summary
      creator: {
        connect: { id: creatorId },
      },
    },
    include: {
      creator: { select: { id: true, name: true } },
    },
  });
};

export const getAllSummaries = async (userId?: string) => {
  // Only fetch summaries created by the specified user
  const whereClause = userId ? { creatorId: userId } : {};

  return prisma.summary.findMany({
    where: whereClause,
    orderBy: { createdAt: 'desc' },
    include: {
      creator: { select: { id: true, name: true } },
    },
  });
};

// --- TODO: Add functions for getting a specific summary, deleting, etc. --- 